<a href="https://colab.research.google.com/github/Ramiz1336/Pytorch/blob/main/Creating%20First%20Tensor%20.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.1+cu118


**Introduction To Tensors **

Creating Tensors

In [4]:
#scalar
scalar =torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
#Got Tensor
scalar.item()

7

In [7]:
#vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [8]:
vector.shape

torch.Size([2])

In [14]:
#Matrix
MATRIX = torch.tensor([[7,8],
 [9,10]]);
MATRIX


tensor([[ 7,  8],
        [ 9, 10]])

In [15]:
MATRIX.ndim

2

In [3]:
#Tensor
TENSOR = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [4]:
TENSOR.ndim

3

In [5]:
TENSOR.shape

torch.Size([1, 3, 3])

In [7]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

# New section

# New section